### PR TITLE
Ignore non diagnosticsRef ids

### PR DESCRIPTION
**Pull request by keith**
Potential fix for https://github.com/google/xctestrunner/issues/23

### CODE REVIEW

**Comment by keith** [comment]
I first tried handling the other types, but there are some other failures for those

**Comment by keith** [comment]
@albertdai can you review?

**Comment by albertdai** [comment]
Thanks for contributing that.

Is this change urgent for you? If yes, I could cut a new release for that.

**Comment by keith** [comment]
It would be great if you could, we see a lot of failures caused by this, but also if you're open to https://github.com/google/xctestrunner/pull/22 I'd love to see that in the release too

**Pull request merged**
