### PR TITLE
Allow running ios test runner as an external repo

### PR DESCRIPTION
**Pull request by segiddins**
Enables https://github.com/bazelbuild/rules_apple/pull/906, fixing #15 & #19 

It's possible I missed some things with the PY3 migration, but there were no tests to check against in this repo, and all the tests in rules_apple passed

### CODE REVIEW

**Comment by segiddins** [comment]
cc @albertdai. I know these are big changes, but I think it'll make consuming xctestrunner from bazel a lot more approachable, in turn making it easier for folks to iterate on xctestrunner

**Comment by albertdai** [comment]
Thanks Samuel for making the change. I will review the commits in the next two days.

**Comment by segiddins** [comment]
@albertdai let me know if there's anything else I should add to this!

**Comment by segiddins** [comment]
@albertdai just wanted to circle back and see if there's anything I should do here?

**Comment by brentleyjones** [comment]
@albertdai Pinging again. Thanks!

**Comment by justinseanmartin** [comment]
Bump, it would be great to not have to fork this repo. Thanks!

**Comment by dmaclach** [comment]
@albertdai soft ping on this

**Review by albertdai — APPROVED** [review]

**Review by albertdai — APPROVED** [review]

**Comment by albertdai** [comment]
Thanks Samuel for the contribution.

**Pull request merged**
