### PR TITLE
Create .xctestrun file instead of .plist

### PR DESCRIPTION
**Pull request by aircraft-cerier**

### CODE REVIEW

**Comment by keith** [comment]
does just changing the extension fix this? I assume this is to fix https://github.com/google/xctestrunner/issues/60 ?

**Comment by marcosgriselli** [comment]
This change fixes things for us in Xcode 15 beta 7.

**Comment by keith** [comment]
@tirodkar can you help land?

**Review by keith — APPROVED** [review]

**Comment by aircraft-cerier** [comment]
All good now, thanks!

**Pull request merged**
