### PR TITLE
Do not rely on repository imports

### PR DESCRIPTION
**Pull request by fmeum**
With Bzlmod, on disk ("canonical") repository names are an implementation detail and can thus no longer be used in Python imports. Instead, similar to non-Bazel Python projects, the import paths should be based on actual directories under the repo root - all repo roots are implicitly added to the Python path by Bazel.

Further context at https://github.com/bazelbuild/bazel-central-registry/pull/269#issuecomment-1308693116

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
This fixes my example project that was failing with the error in the other thread. With an empty `WORKSPACE` and this `MODULE.bazel`:
```
bazel_dep(name = "rules_apple")
local_path_override(
    module_name = "rules_apple",
    path = "/Users/me/src/rules_apple",
)
```

I can now successfully run: `bazelisk test --enable_bzlmod @rules_apple//examples/ios/Squarer:SquarerTests` which was failing before this patch.

**Comment by keith** [comment]
Thanks for testing @BalestraPatrick, lgtm. @fmeum note that only googlers can merge here

**Comment by fmeum** [comment]
@albertdai Could you review this PR? It's required to make xctestrunner usable with [Bzlmod](https://bazel.build/build/bzlmod), which will be released with Bazel 6.

**Comment by fmeum** [comment]
@albertdai Friendly ping

**Comment by keith** [comment]
cc @tirodkar

**Comment by tirodkar** [comment]
@keith Can I get a quick explanation of why this is needed? It looks like you're changing the folder structure here so that nothing can be at the root directory. We'd have to do some changes internally to our structure as well to sync this in.

There are also conflicts here that perhaps we could address? :)

**Comment by keith** [comment]
@fmeum can you update

**Comment by fmeum** [comment]
@tirodkar @me11kiy Rebased onto master. The PR description has most of the context, but the summary is that with the new external dependency management system Bzlmod stabilized in Bazel 6, repository names are mangled dynamically using repository mappings. As a result, runfiles-based dynamic languages such as Python can't statically import paths that contain repository names anymore. Hence, and also to improve consistency with Python repos created by rules_python's pip support, import paths should be repository root relative. In this case, since the import path would be highly ambiguous that way, I moved everything into a distinctive top-level directory.

**Comment by tirodkar** [comment]
Is there a chance of this breaking existing users or would it work seamlessly for all bazel users?

**Comment by fmeum** [comment]
> Is there a chance of this breaking existing users or would it work seamlessly for all bazel users?

Since the top-level directory has the same name as the repository in non-Bzlmod land, users that did `import xctestrunner.foobar` can continue to do so. I thus expect no breakage. If someone did e.g. `import simulator_control.foobar` or `import shared.foobar` directly, that usage would break.

**Comment by tirodkar** [comment]
I am not quite aware of anyone using it that way. If you and @keith do not expect any breakages then I'm fine with merging this.

**Comment by keith** [comment]
folks shouldn't be importing these python files directly, so im not worried about it

**Comment by tirodkar** [comment]
This needs a rebase again folks as there's conflicts. Sorry.

**Comment by fmeum** [comment]
@tirodkar Rebased.

**Review by me11kiy — APPROVED** [review]

**Pull request merged**
